from __future__ import annotations
from typing import Mapping
from .models import KnowledgeArticle

GZCTF_ARTICLES: dict[str, KnowledgeArticle] = {
    "architecture": KnowledgeArticle(
        id="architecture",
        title="GZCTF Attack & Defense Engine Architecture",
        summary="Round engine, container reconciliation, network bridges, and schedulers.",
        category="gzctf",
        tags=("gzctf", "architecture", "engine"),
        content="""# GZCTF Attack & Defense Architecture

Based on official GZCTF engine specifications:

GZCTF extends jeopardy CTF with a native Attack & Defense engine (`ChallengeType: AttackDefense`).

## 1. Round & Tick Model
- **Warmup Window** (`Game.AdWarmupSeconds`, default 1800s / 30 mins):
  When a game goes live, round 1 does not start immediately. Teams use this time to connect via WireGuard VPN and inspect their boxes. During warmup, no flags exist, SLA is not checked, and `/Targets` returns an empty list.
- **Tick Advance & Duration** (`Game.AdTickSeconds`, `AdRoundScheduler`):
  Evaluates every 5 seconds. Tick length is defined by `Game.AdTickSeconds` (default 60s). When the active round's `EndsAt` timestamp is reached, it triggers `AdRoundService.AdvanceAsync`.

- **Atomic Advance**:
  In a single database transaction, the engine inserts the new `AdRound` record and mints fresh per-team flags. After commit, flags are planted into team containers.

## 2. Container Topology & Lifecycle
- **One Container per (Team, Challenge)**:
  Every accepted team gets its own private instance of each enabled challenge.
- **Reconciliation Loop** (`AdContainerManager`):
  Runs every 15 seconds. Verifies all expected containers are live. Re-launches dead containers automatically.

## 3. Network Modes & Isolation
- Challenges configure `ad.allowEgress`:
  * **Open Bridge** (`ad.allowEgress: true`, default): Box can reach the internet (hardened to deny cloud metadata and internal ranges). Teams reach each other via WireGuard VPN.
  * **Isolated Bridge** (`ad.allowEgress: false`): Deny-all egress; accessible solely through the competition WireGuard VPN network.
""",
    ),
    "flag_mechanics": KnowledgeArticle(
        id="flag_mechanics",
        title="GZCTF Flag Delivery & Lifecycle",
        summary="How flags are generated, planted via bind-mounts, and expired.",
        category="gzctf",
        tags=("gzctf", "flags", "lifecycle"),
        content="""# GZCTF Flag Delivery & Lifecycle

## Flag Format
Flags generated by GZCTF A&D follow the standard format:
```text
flag{<24 random url-safe-base64 bytes>}
```

## How Flags Are Delivered to Containers
Unlike Jeopardy challenges, **there is NO static `GZCTF_FLAG` environment variable** inside an A&D challenge container (an env var would freeze at creation time and go stale).

Instead, challenge code is informed of the flag location via the **`GZCTF_FLAG_FILE`** environment variable:
- **Docker Environments**: Host file delivered via a read-only host-backed **bind mount** (`:ro`) at `/flag`. Root-owned (`644`). The platform updates the host file each tick, instantly reflecting in the container without container restart.
- **Kubernetes Environments**: Written to `/gzctf-flag/flag` by a pull-model sidecar polling the engine.


```bash
# Challenge / service code reads the active flag:
cat "$GZCTF_FLAG_FILE"  # Docker: /flag, K8s: /gzctf-flag/flag
```

## Flag Lifetime & Expiration
- Flags remain valid for `Game.AdFlagLifetimeTicks` rounds (typically 3 to 5 rounds).
- Submissions older than `(currentRound - lifetime + 1)` are rejected as `expired`.
- **Operator Implication**: Stolen flags must be submitted quickly! Hoarding flags across multiple rounds leads to expiration and zero points.
""",
    ),
    "sla_checker": KnowledgeArticle(
        id="sla_checker",
        title="GZCTF SLA Checker & Health Evaluation",
        summary="Checker cadence, exit codes, push/pull checks, and avoiding SLA penalties.",
        category="gzctf",
        tags=("gzctf", "sla", "checker"),
        content="""# GZCTF SLA Checker & Health Evaluation

## Checker Execution Model
- The SLA checker operates independently of the round advance scheduler via `AdCheckerService` (running on a ~10-second background cadence).
- A slow checker cannot block the round advance.
- The platform spins up dedicated checker containers that connect to the team's target port.

## Checker Contract
1. **Target Verification**: The checker attempts standard service interaction (HTTP request, socket handshake, database query).
2. **Putflag / Getflag**: In challenges requiring state verification, the checker plants a unique check string or attempts to retrieve a test token.
3. **Exit Code Interpretation**:
   - Exit `0`: Service healthy, SLA awarded for the tick.
   - Exit `1` or non-zero: Service failed health check, SLA lost for the tick.
   - Timeout: Treated as failure (SLA lost).

## Operator Takeaway
When developing patches on your team VM, run a local imitation of the checker script to verify that legitimate application functionality remains 100% operational before restarting the live service.
""",
    ),
    "competition_ops": KnowledgeArticle(
        id="competition_ops",
        title="GZCTF Competition Operations & Setup",
        summary="WireGuard VPN setup, SSH access, competition domain, and submission rules.",
        category="gzctf",
        tags=("gzctf", "operations", "wireguard", "ssh"),
        content="""# GZCTF Competition Operations & Setup

## 1. Network Connectivity (WireGuard VPN)
- The competition arena is hosted in an isolated network reachable via WireGuard.
- Download the client configuration (`wg0.conf`) from the competition portal.
- Connect using `wg-quick up wg0` or NetworkManager.
- Verify connectivity: `wg show` and ping the gateway or your designated VM.

## 2. Server Access (SSH Keys)
- Every team is provisioned a VM accessed via SSH key authentication.
- Recommended SSH configuration:
  ```bash
  ssh -i ~/.ssh/id_rsa -p <port> <user>@<team_vm_ip>
  ```
- All team VMs start with identical code. Inspect `/var/www`, `/opt`, or home directory to locate challenge services.

## 3. Flag Submission Workflow
- Flags can be submitted via the platform UI or programmatic API endpoint.
- Respect submission rate limits; automated submission scripts should submit unique flags immediately upon extraction.
- Strict anti-cheat: Sharing flags or credentials between teams results in immediate disqualification.
""",
    ),
}

def get_gzctf_article(article_id: str) -> KnowledgeArticle | None:
    return GZCTF_ARTICLES.get(article_id)

def list_gzctf_articles() -> tuple[KnowledgeArticle, ...]:
    return tuple(GZCTF_ARTICLES.values())
