from __future__ import annotations
from typing import Mapping
from .models import KnowledgeArticle

GZCTF_ARTICLES: dict[str, KnowledgeArticle] = {
    "architecture": KnowledgeArticle(
        id="architecture",
        title="GZCTF Attack & Defense Engine Architecture",
        summary="Round engine, container reconciliation, network bridges, and schedulers.",
        category="gzctf",
        tags=("gzctf", "architecture", "engine"),
        content="""# GZCTF Attack & Defense Architecture

Based on official GZCTF engine specifications:

GZCTF extends jeopardy CTF with a native Attack & Defense engine (`ChallengeType: AttackDefense`).

## 1. Round & Tick Model
- **Warmup Window** (`Game.AdWarmupSeconds`, default 1800s / 30 mins):
  When a game goes live, round 1 does not start immediately. Teams use this time to connect via WireGuard VPN and inspect their boxes. During warmup, no flags exist, SLA is not checked, and `/Targets` returns an empty list.
- **Tick Advance & Duration** (`Game.AdTickSeconds`, `AdRoundScheduler`):
  Evaluates every 5 seconds. Tick length is defined by `Game.AdTickSeconds` (default 60s). When the active round's `EndsAt` timestamp is reached, it triggers `AdRoundService.AdvanceAsync`.

- **Atomic Advance**:
  In a single database transaction, the engine inserts the new `AdRound` record and mints fresh per-team flags. After commit, flags are planted into team containers.

## 2. Container Topology & Lifecycle
- **One Container per (Team, Challenge)**:
  Every accepted team gets its own private instance of each enabled challenge.
- **Reconciliation Loop** (`AdContainerManager`):
  Runs every 15 seconds. Verifies all expected containers are live. Re-launches dead containers automatically.

## 3. Network Modes & Isolation
- Challenges configure `ad.allowEgress`:
  * **Open Bridge** (`ad.allowEgress: true`, default): Box can reach the internet (hardened to deny cloud metadata and internal ranges). Teams reach each other via WireGuard VPN.
  * **Isolated Bridge** (`ad.allowEgress: false`): Deny-all egress; accessible solely through the competition WireGuard VPN network.
""",
    ),
    "flag_mechanics": KnowledgeArticle(
        id="flag_mechanics",
        title="GZCTF Flag Delivery & Lifecycle",
        summary="How flags are generated, planted via bind-mounts, and expired.",
        category="gzctf",
        tags=("gzctf", "flags", "lifecycle"),
        content="""# GZCTF Flag Delivery & Lifecycle

## Flag Format
Flags generated by GZCTF A&D follow the standard format:
```text
flag{<24 random url-safe-base64 bytes>}
```

## How Flags Are Delivered to Containers
Unlike Jeopardy challenges, **there is NO static `GZCTF_FLAG` environment variable** inside an A&D challenge container (an env var would freeze at creation time and go stale).

Instead, challenge code is informed of the flag location via the **`GZCTF_FLAG_FILE`** environment variable:
- **Docker Environments**: Host file delivered via a read-only host-backed **bind mount** (`:ro`) at `/flag`. Root-owned (`644`). The platform updates the host file each tick, instantly reflecting in the container without container restart.
- **Kubernetes Environments**: Written to `/gzctf-flag/flag` by a pull-model sidecar polling the engine.


```bash
# Challenge / service code reads the active flag:
cat "$GZCTF_FLAG_FILE"  # Docker: /flag, K8s: /gzctf-flag/flag
```

## Flag Lifetime & Expiration
- Flags remain valid for `Game.AdFlagLifetimeTicks` rounds (typically 3 to 5 rounds).
- Submissions older than `(currentRound - lifetime + 1)` are rejected as `expired`.
- **Operator Implication**: Stolen flags must be submitted quickly! Hoarding flags across multiple rounds leads to expiration and zero points.
""",
    ),
    "sla_checker": KnowledgeArticle(
        id="sla_checker",
        title="GZCTF SLA Checker & Health Evaluation",
        summary="Checker cadence, enochecker3 exit codes, and exact scoring calculations.",
        category="gzctf",
        tags=("gzctf", "sla", "checker", "scoring"),
        content="""# GZCTF SLA Checker & Health Evaluation

## Checker Execution Model
- The SLA checker operates independently of the round advance scheduler via `AdCheckerService` (running on a 10-second background cadence, `MaxCheckAttempts = 3`, `RetryDelay = 1.5s`).
- A slow checker cannot block the round advance.
- The platform spins up dedicated checker containers that connect to the team's target port.

## Checker Contract & Exit Code Mapping
In GZCTF's check runner (`AdCheckMapping`), check status is resolved directly from process exit codes:
- **Custom Checker (enochecker3 standard contract)**:
  * Exit `0` -> `Ok`: Service is operational, responding correctly, and passed functional tests.
  * Exit `1` -> `Mumble`: Service reachable but returned invalid/corrupted data or violated API schema.
  * Exit `2` -> `Offline`: Service port connection refused, timed out, or process down.
  * Exit `3` or unhandled -> `InternalError`: Infrastructure or checker failure (earns 0 this tick, but does not retroactively drag down score).
- **Built-in TCP Probe (when no custom checker is configured)**:
  * Exit `0` -> `Ok`
  * Any non-zero exit -> `Offline`

## Exact GZCTF Scoring Math (`AdScoring.cs`)
- Score formula: `Total = Attack + SLA - DefenseLoss`
- **Attack Points**: `Σ (AttackPool / k)` where `k` is the count of teams that stole that specific flag (`AttackPool = 1.0`). Rewards unique exploits.
- **Defense Loss**: `DefensePool * compromisedFlags` (`DefensePool = 1.0`). Penalized once per distinct compromised flag regardless of how many adversaries stole it.
- **SLA Points**: `Σ (TickCredit * SlaFieldFactor)` where:
  * `TickCredit`: `1.0` (clean Ok), `0.5` (recovering: Ok after Offline/Mumble), `0.0` (Offline, Mumble, or InternalError).
  * `SlaFieldFactor`: `sqrt(max(1, activeTeams))`.
""",
    ),
    "competition_ops": KnowledgeArticle(
        id="competition_ops",
        title="GZCTF Competition Operations & Setup",
        summary="Generic GZCTF platform mechanics vs specific tournament deployment profiles.",
        category="gzctf",
        tags=("gzctf", "operations", "wireguard", "ssh"),
        content="""# GZCTF Competition Operations & Setup

## 1. Generic GZCTF Architecture vs Competition Deployment
It is essential to distinguish built-in platform features from event-specific rules:
- **Universal GZCTF Engine Capabilities**:
  * Network plane: WireGuard sidecar (`wg-config`, `AdWireGuardSyncService`, UDP port 51820).
  * SSH jump bastion (`ssh-jump` on port 22022) with keyed accounts (`<challengeId>@jump-host`).
  * Dedicated API endpoints: `/api/Game/{id}/Ad/Vpn/Config`, `/api/Game/{id}/Ad/Targets`, `/api/Game/{id}/Ad/Submit`.
- **Tournament / Specific Deployment** (e.g. Grand Final at `jjz.jatimprov.go.id`):
  * Platform domain: `jjz.jatimprov.go.id`.
  * Connectivity: WireGuard tunnel (typically client interface `wg0`).
  * Host access: SSH key-based access to provisioned team VMs.
  * Round duration: Configured between 1 and 5 minutes per tick (governed by `Game.AdTickSeconds`).
  * Tournament policy: Strict prohibition of infrastructure DoS and anti-collusion between teams.

## 2. Operator Workflow on Competition Day
1. Bring up VPN interface: `sudo wg-quick up wg0` and verify with `wg show`.
2. Access team VM via SSH: `ssh -i ~/.ssh/id_rsa -p <port> <user>@<team_vm_ip>`.
3. Inspect and backup service source code before applying changes.
4. Keep patches surgical to preserve `Ok` status and avoid `Mumble` or `Offline` SLA penalties.
""",
    ),
}

def get_gzctf_article(article_id: str) -> KnowledgeArticle | None:
    return GZCTF_ARTICLES.get(article_id)

def list_gzctf_articles() -> tuple[KnowledgeArticle, ...]:
    return tuple(GZCTF_ARTICLES.values())
